FROM apache/superset:latest

USER root

RUN pip install \
    duckdb==1.1.3 \
    duckdb-engine \
    "sqlalchemy<2,>=1.4" \
    "greenlet<=3.1.1,>=3.0.3" \
    "packaging<26,>=21" \
    --target=/app/.venv/lib/python3.10/site-packages

USER superset
